name: tefriciye
description: A new Flutter project.

publish_to: 'none'
 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core
  flutter_riverpod: ^2.4.0
  # Util
  flextensions: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^2.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/img/
